val m :
     local_path:string
  -> uri_prefix:string
  -> ?headers:Httpaf.Headers.t
  -> ?etag_of_fname:(string -> string)
  -> unit
  -> Opium_kernel.Rock.Middleware.t
(** Middleware serves all files (recursively) in the [local_path] directory
    under the [uri_prefix] url. The responses contain a [Content-type] header
    that is auto-detected based on the file extension using the
    {!Magic_mime.lookup} function. Additional headers can be provided through
    [headers].

    If [etag_of_fname] is provided, the response will contain an [ETag] header.
    If the request contains an [If-None-Match] header with an [ETag] equal to
    that generated by [etag_of_fname], this middleware will respond with
    [304 Not Modified]. *)
