name: OpiumTest
on:
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ocaml-version: ['4.11.1', '4.10.1', '4.09.1', '4.08.1' ]
    steps:
      - uses: actions/checkout@v2
      - uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
      - name: Install dependencies
        run: |
          opam pin add opium_kernel.dev -n .
          opam pin add opium.dev -n .
          opam depext -yt opium_kernel
          opam depext -yt opium
          opam install -t . --deps-only
          opam install -y ppx_sexp_conv base64 ppx_yojson_conv
      - name: Build
        run: opam exec -- dune build
      - name: Run tests
        run: opam exec -- dune runtest
      - name: Build examples
        run: opam exec -- dune build @examples
